version: "3.7"
services:
  webserver:
    build: docker/nginx
    container_name: webserver
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${NGINX_EXTERNAL_HTTP_PORT}:80"
      - "${NGINX_EXTERNAL_HTTPS_PORT}:443"
    restart: unless-stopped

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PHP_IDE_CONFIG: serverName=github-repos-ranking
    restart: unless-stopped

networks:
  default:
    ipam:
      driver: default
      config:
        -   subnet: 172.10.1.0/24
