name: CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: php-cs-fixer
      run: php vendor/bin/php-cs-fixer fix -v --using-cache=no --dry-run
      
    - name: php-stan
      run: php vendor/bin/phpstan analyse -c phpstan.neon
      
    - name: unit-tests
      run: php bin/phpunit
